// Agora deck. Free.
var deck = {
  "id": "bundled:spanish",
  "name": "Spanish 250",
  "lang": "es",
  "cards": [
    { "id": "es-0001", "front": "hola", "back": "hello", "example": "Hola, ¿cómo estás?" },
    { "id": "es-0002", "front": "adiós", "back": "goodbye", "example": "Adiós, hasta mañana." },
    { "id": "es-0003", "front": "buenos días", "back": "good morning", "example": "Buenos días, señora." },
    { "id": "es-0004", "front": "buenas tardes", "back": "good afternoon", "example": "Buenas tardes a todos." },
    { "id": "es-0005", "front": "buenas noches", "back": "good night", "example": "Buenas noches, que descanses." },
    { "id": "es-0006", "front": "por favor", "back": "please", "example": "Un café, por favor." },
    { "id": "es-0007", "front": "gracias", "back": "thank you", "example": "Muchas gracias por tu ayuda." },
    { "id": "es-0008", "front": "de nada", "back": "you're welcome", "example": "De nada, fue un placer." },
    { "id": "es-0009", "front": "perdón", "back": "sorry / excuse me", "example": "Perdón, no te oí." },
    { "id": "es-0010", "front": "lo siento", "back": "I'm sorry", "example": "Lo siento mucho por el retraso." },
    { "id": "es-0011", "front": "sí", "back": "yes", "example": "Sí, me gusta mucho." },
    { "id": "es-0012", "front": "no", "back": "no", "example": "No, gracias." },
    { "id": "es-0013", "front": "bienvenido", "back": "welcome", "example": "Bienvenido a nuestra casa." },
    { "id": "es-0014", "front": "mucho gusto", "back": "nice to meet you", "example": "Mucho gusto, soy Ana." },
    { "id": "es-0015", "front": "¿cómo estás?", "back": "how are you?", "example": "Hola Pedro, ¿cómo estás?" },
    { "id": "es-0016", "front": "hasta luego", "back": "see you later", "example": "Me voy ya, hasta luego." },
    { "id": "es-0017", "front": "cero", "back": "zero", "example": "El marcador está en cero." },
    { "id": "es-0018", "front": "uno", "back": "one", "example": "Solo quiero uno." },
    { "id": "es-0019", "front": "dos", "back": "two", "example": "Tengo dos hermanos." },
    { "id": "es-0020", "front": "tres", "back": "three", "example": "Son las tres de la tarde." },
    { "id": "es-0021", "front": "cuatro", "back": "four", "example": "La mesa tiene cuatro patas." },
    { "id": "es-0022", "front": "cinco", "back": "five", "example": "Llego en cinco minutos." },
    { "id": "es-0023", "front": "seis", "back": "six", "example": "El niño tiene seis años." },
    { "id": "es-0024", "front": "siete", "back": "seven", "example": "La semana tiene siete días." },
    { "id": "es-0025", "front": "ocho", "back": "eight", "example": "Trabajo ocho horas al día." },
    { "id": "es-0026", "front": "nueve", "back": "nine", "example": "Faltan nueve días." },
    { "id": "es-0027", "front": "diez", "back": "ten", "example": "Hay diez personas aquí." },
    { "id": "es-0028", "front": "once", "back": "eleven", "example": "El tren sale a las once." },
    { "id": "es-0029", "front": "doce", "back": "twelve", "example": "El año tiene doce meses." },
    { "id": "es-0030", "front": "trece", "back": "thirteen", "example": "Tengo trece monedas." },
    { "id": "es-0031", "front": "catorce", "back": "fourteen", "example": "Mi prima cumple catorce años." },
    { "id": "es-0032", "front": "quince", "back": "fifteen", "example": "Espera quince minutos." },
    { "id": "es-0033", "front": "dieciséis", "back": "sixteen", "example": "Hay dieciséis estudiantes." },
    { "id": "es-0034", "front": "diecisiete", "back": "seventeen", "example": "Mi hermano tiene diecisiete años." },
    { "id": "es-0035", "front": "dieciocho", "back": "eighteen", "example": "Se vota a los dieciocho años." },
    { "id": "es-0036", "front": "diecinueve", "back": "nineteen", "example": "Quedan diecinueve días." },
    { "id": "es-0037", "front": "veinte", "back": "twenty", "example": "El libro cuesta veinte euros." },
    { "id": "es-0038", "front": "treinta", "back": "thirty", "example": "Mi padre tiene treinta años." },
    { "id": "es-0039", "front": "cuarenta", "back": "forty", "example": "Hay cuarenta sillas en la sala." },
    { "id": "es-0040", "front": "cincuenta", "back": "fifty", "example": "El billete es de cincuenta euros." },
    { "id": "es-0041", "front": "sesenta", "back": "sixty", "example": "Mi abuela tiene sesenta años." },
    { "id": "es-0042", "front": "setenta", "back": "seventy", "example": "El camino mide setenta metros." },
    { "id": "es-0043", "front": "ochenta", "back": "eighty", "example": "Vinieron ochenta invitados." },
    { "id": "es-0044", "front": "noventa", "back": "ninety", "example": "Faltan noventa páginas." },
    { "id": "es-0045", "front": "cien", "back": "one hundred", "example": "Tengo cien dólares." },
    { "id": "es-0046", "front": "mil", "back": "one thousand", "example": "El coche cuesta mil euros." },
    { "id": "es-0047", "front": "lunes", "back": "Monday", "example": "El lunes empiezo a trabajar." },
    { "id": "es-0048", "front": "martes", "back": "Tuesday", "example": "Tengo cita el martes." },
    { "id": "es-0049", "front": "miércoles", "back": "Wednesday", "example": "El miércoles vamos al cine." },
    { "id": "es-0050", "front": "jueves", "back": "Thursday", "example": "Los jueves estudio inglés." },
    { "id": "es-0051", "front": "viernes", "back": "Friday", "example": "El viernes salgo con amigos." },
    { "id": "es-0052", "front": "sábado", "back": "Saturday", "example": "El sábado descanso en casa." },
    { "id": "es-0053", "front": "domingo", "back": "Sunday", "example": "El domingo visito a mi familia." },
    { "id": "es-0054", "front": "enero", "back": "January", "example": "Mi cumpleaños es en enero." },
    { "id": "es-0055", "front": "febrero", "back": "February", "example": "Febrero es el mes más corto." },
    { "id": "es-0056", "front": "marzo", "back": "March", "example": "En marzo empieza la primavera." },
    { "id": "es-0057", "front": "abril", "back": "April", "example": "Llueve mucho en abril." },
    { "id": "es-0058", "front": "mayo", "back": "May", "example": "Nos casamos en mayo." },
    { "id": "es-0059", "front": "junio", "back": "June", "example": "Las clases terminan en junio." },
    { "id": "es-0060", "front": "julio", "back": "July", "example": "En julio hace mucho calor." },
    { "id": "es-0061", "front": "agosto", "back": "August", "example": "Viajamos a la playa en agosto." },
    { "id": "es-0062", "front": "septiembre", "back": "September", "example": "El curso empieza en septiembre." },
    { "id": "es-0063", "front": "octubre", "back": "October", "example": "En octubre caen las hojas." },
    { "id": "es-0064", "front": "noviembre", "back": "November", "example": "Noviembre es un mes frío." },
    { "id": "es-0065", "front": "diciembre", "back": "December", "example": "La fiesta es en diciembre." },
    { "id": "es-0066", "front": "hoy", "back": "today", "example": "Hoy tengo mucho trabajo." },
    { "id": "es-0067", "front": "mañana", "back": "tomorrow", "example": "Mañana voy al médico." },
    { "id": "es-0068", "front": "ayer", "back": "yesterday", "example": "Ayer comí con mi familia." },
    { "id": "es-0069", "front": "ahora", "back": "now", "example": "Ahora no puedo hablar." },
    { "id": "es-0070", "front": "siempre", "back": "always", "example": "Siempre llego temprano." },
    { "id": "es-0071", "front": "nunca", "back": "never", "example": "Nunca como carne." },
    { "id": "es-0072", "front": "el día", "back": "day", "example": "El día está muy soleado." },
    { "id": "es-0073", "front": "la semana", "back": "week", "example": "La semana pasada llovió." },
    { "id": "es-0074", "front": "el mes", "back": "month", "example": "Este mes voy a ahorrar." },
    { "id": "es-0075", "front": "el año", "back": "year", "example": "El año tiene doce meses." },
    { "id": "es-0076", "front": "la hora", "back": "hour / time", "example": "¿Qué hora es?" },
    { "id": "es-0077", "front": "temprano", "back": "early", "example": "Me levanto muy temprano." },
    { "id": "es-0078", "front": "tarde", "back": "late", "example": "Llegaste tarde otra vez." },
    { "id": "es-0079", "front": "qué", "back": "what", "example": "¿Qué quieres comer?" },
    { "id": "es-0080", "front": "quién", "back": "who", "example": "¿Quién es esa mujer?" },
    { "id": "es-0081", "front": "cuándo", "back": "when", "example": "¿Cuándo llegas a casa?" },
    { "id": "es-0082", "front": "dónde", "back": "where", "example": "¿Dónde está el baño?" },
    { "id": "es-0083", "front": "por qué", "back": "why", "example": "¿Por qué estás triste?" },
    { "id": "es-0084", "front": "cómo", "back": "how", "example": "¿Cómo se dice esto?" },
    { "id": "es-0085", "front": "cuánto", "back": "how much", "example": "¿Cuánto cuesta el café?" },
    { "id": "es-0086", "front": "cuál", "back": "which", "example": "¿Cuál prefieres, té o café?" },
    { "id": "es-0087", "front": "yo", "back": "I", "example": "Yo vivo en Madrid." },
    { "id": "es-0088", "front": "tú", "back": "you (informal)", "example": "Tú hablas muy bien." },
    { "id": "es-0089", "front": "él", "back": "he", "example": "Él trabaja en un banco." },
    { "id": "es-0090", "front": "ella", "back": "she", "example": "Ella es mi profesora." },
    { "id": "es-0091", "front": "usted", "back": "you (formal)", "example": "¿Usted habla inglés?" },
    { "id": "es-0092", "front": "nosotros", "back": "we", "example": "Nosotros vamos al parque." },
    { "id": "es-0093", "front": "ellos", "back": "they", "example": "Ellos viven cerca de aquí." },
    { "id": "es-0094", "front": "me", "back": "me", "example": "Me gusta este libro." },
    { "id": "es-0095", "front": "ser", "back": "to be (permanent)", "example": "Quiero ser médico." },
    { "id": "es-0096", "front": "estar", "back": "to be (state/location)", "example": "Voy a estar en casa." },
    { "id": "es-0097", "front": "tener", "back": "to have", "example": "Tengo dos perros." },
    { "id": "es-0098", "front": "hacer", "back": "to do / make", "example": "Tengo mucho que hacer hoy." },
    { "id": "es-0099", "front": "ir", "back": "to go", "example": "Voy a ir al mercado." },
    { "id": "es-0100", "front": "ver", "back": "to see / watch", "example": "Quiero ver esa película." },
    { "id": "es-0101", "front": "dar", "back": "to give", "example": "Te voy a dar un regalo." },
    { "id": "es-0102", "front": "saber", "back": "to know (facts)", "example": "No sé la respuesta." },
    { "id": "es-0103", "front": "querer", "back": "to want / love", "example": "Quiero un vaso de agua." },
    { "id": "es-0104", "front": "poder", "back": "to be able to", "example": "No puedo abrir la puerta." },
    { "id": "es-0105", "front": "decir", "back": "to say / tell", "example": "¿Qué quieres decir?" },
    { "id": "es-0106", "front": "hablar", "back": "to speak", "example": "Hablo español todos los días." },
    { "id": "es-0107", "front": "comer", "back": "to eat", "example": "Vamos a comer pizza." },
    { "id": "es-0108", "front": "beber", "back": "to drink", "example": "Quiero beber agua fría." },
    { "id": "es-0109", "front": "vivir", "back": "to live", "example": "Quiero vivir cerca del mar." },
    { "id": "es-0110", "front": "trabajar", "back": "to work", "example": "Trabajo en una oficina." },
    { "id": "es-0111", "front": "estudiar", "back": "to study", "example": "Estudio inglés por la noche." },
    { "id": "es-0112", "front": "comprar", "back": "to buy", "example": "Voy a comprar pan." },
    { "id": "es-0113", "front": "leer", "back": "to read", "example": "Me gusta leer novelas." },
    { "id": "es-0114", "front": "escribir", "back": "to write", "example": "Voy a escribir una carta." },
    { "id": "es-0115", "front": "dormir", "back": "to sleep", "example": "Necesito dormir ocho horas." },
    { "id": "es-0116", "front": "comprender", "back": "to understand", "example": "No comprendo la pregunta." },
    { "id": "es-0117", "front": "venir", "back": "to come", "example": "¿Puedes venir mañana?" },
    { "id": "es-0118", "front": "llegar", "back": "to arrive", "example": "El tren va a llegar tarde." },
    { "id": "es-0119", "front": "salir", "back": "to leave / go out", "example": "Salgo de casa a las ocho." },
    { "id": "es-0120", "front": "abrir", "back": "to open", "example": "¿Puedes abrir la ventana?" },
    { "id": "es-0121", "front": "cerrar", "back": "to close", "example": "Voy a cerrar la puerta." },
    { "id": "es-0122", "front": "gustar", "back": "to like (be pleasing)", "example": "Me gusta el chocolate." },
    { "id": "es-0123", "front": "pensar", "back": "to think", "example": "Pienso que tienes razón." },
    { "id": "es-0124", "front": "necesitar", "back": "to need", "example": "Necesito ayuda con esto." },
    { "id": "es-0125", "front": "usar", "back": "to use", "example": "Uso el teléfono cada día." },
    { "id": "es-0126", "front": "esperar", "back": "to wait / hope", "example": "Te espero en la puerta." },
    { "id": "es-0127", "front": "caminar", "back": "to walk", "example": "Me gusta caminar por el parque." },
    { "id": "es-0128", "front": "escuchar", "back": "to listen", "example": "Escucho música en el coche." },
    { "id": "es-0129", "front": "jugar", "back": "to play", "example": "Los niños quieren jugar fuera." },
    { "id": "es-0130", "front": "la familia", "back": "family", "example": "Mi familia es muy grande." },
    { "id": "es-0131", "front": "la madre", "back": "mother", "example": "Mi madre cocina muy bien." },
    { "id": "es-0132", "front": "el padre", "back": "father", "example": "Mi padre trabaja mucho." },
    { "id": "es-0133", "front": "el hijo", "back": "son", "example": "Su hijo tiene cinco años." },
    { "id": "es-0134", "front": "la hija", "back": "daughter", "example": "Mi hija estudia medicina." },
    { "id": "es-0135", "front": "el hermano", "back": "brother", "example": "Mi hermano vive en México." },
    { "id": "es-0136", "front": "la hermana", "back": "sister", "example": "Mi hermana es enfermera." },
    { "id": "es-0137", "front": "el amigo", "back": "friend (male)", "example": "Mi amigo viene esta noche." },
    { "id": "es-0138", "front": "la amiga", "back": "friend (female)", "example": "Voy al cine con mi amiga." },
    { "id": "es-0139", "front": "el niño", "back": "child / boy", "example": "El niño juega en el jardín." },
    { "id": "es-0140", "front": "la mujer", "back": "woman / wife", "example": "Esa mujer es mi vecina." },
    { "id": "es-0141", "front": "el hombre", "back": "man", "example": "El hombre lee el periódico." },
    { "id": "es-0142", "front": "la comida", "back": "food / meal", "example": "La comida está deliciosa." },
    { "id": "es-0143", "front": "el agua", "back": "water", "example": "Bebo mucha agua al día." },
    { "id": "es-0144", "front": "el pan", "back": "bread", "example": "Compro pan fresco cada mañana." },
    { "id": "es-0145", "front": "la leche", "back": "milk", "example": "Tomo leche con el café." },
    { "id": "es-0146", "front": "el café", "back": "coffee", "example": "Me gusta el café sin azúcar." },
    { "id": "es-0147", "front": "la fruta", "back": "fruit", "example": "La fruta es muy sana." },
    { "id": "es-0148", "front": "la manzana", "back": "apple", "example": "Como una manzana cada día." },
    { "id": "es-0149", "front": "la carne", "back": "meat", "example": "No como mucha carne." },
    { "id": "es-0150", "front": "el pescado", "back": "fish (food)", "example": "El pescado está muy fresco." },
    { "id": "es-0151", "front": "el huevo", "back": "egg", "example": "Quiero un huevo frito." },
    { "id": "es-0152", "front": "el arroz", "back": "rice", "example": "El arroz con pollo está rico." },
    { "id": "es-0153", "front": "la sal", "back": "salt", "example": "Falta un poco de sal." },
    { "id": "es-0154", "front": "la casa", "back": "house / home", "example": "Mi casa está cerca del parque." },
    { "id": "es-0155", "front": "la puerta", "back": "door", "example": "Cierra la puerta, por favor." },
    { "id": "es-0156", "front": "la ventana", "back": "window", "example": "Abre la ventana, hace calor." },
    { "id": "es-0157", "front": "la mesa", "back": "table", "example": "La comida está en la mesa." },
    { "id": "es-0158", "front": "la silla", "back": "chair", "example": "Siéntate en esta silla." },
    { "id": "es-0159", "front": "la cama", "back": "bed", "example": "Voy a la cama temprano." },
    { "id": "es-0160", "front": "la cocina", "back": "kitchen", "example": "Mi madre está en la cocina." },
    { "id": "es-0161", "front": "el baño", "back": "bathroom", "example": "¿Dónde está el baño?" },
    { "id": "es-0162", "front": "la luz", "back": "light", "example": "Apaga la luz, por favor." },
    { "id": "es-0163", "front": "la llave", "back": "key", "example": "No encuentro mi llave." },
    { "id": "es-0164", "front": "el teléfono", "back": "telephone", "example": "Mi teléfono no funciona." },
    { "id": "es-0165", "front": "el dinero", "back": "money", "example": "No tengo dinero hoy." },
    { "id": "es-0166", "front": "el libro", "back": "book", "example": "Este libro es muy bueno." },
    { "id": "es-0167", "front": "la cabeza", "back": "head", "example": "Me duele la cabeza." },
    { "id": "es-0168", "front": "la mano", "back": "hand", "example": "Lávate las manos antes de comer." },
    { "id": "es-0169", "front": "el ojo", "back": "eye", "example": "Ella tiene los ojos verdes." },
    { "id": "es-0170", "front": "la boca", "back": "mouth", "example": "Abre la boca, por favor." },
    { "id": "es-0171", "front": "el pie", "back": "foot", "example": "Me duele el pie derecho." },
    { "id": "es-0172", "front": "el brazo", "back": "arm", "example": "Se rompió el brazo jugando." },
    { "id": "es-0173", "front": "el corazón", "back": "heart", "example": "El corazón late muy rápido." },
    { "id": "es-0174", "front": "la nariz", "back": "nose", "example": "Tengo la nariz fría." },
    { "id": "es-0175", "front": "la ciudad", "back": "city", "example": "Vivo en una ciudad grande." },
    { "id": "es-0176", "front": "la calle", "back": "street", "example": "La tienda está en esta calle." },
    { "id": "es-0177", "front": "la tienda", "back": "shop / store", "example": "Voy a la tienda a comprar leche." },
    { "id": "es-0178", "front": "el mercado", "back": "market", "example": "Compro verduras en el mercado." },
    { "id": "es-0179", "front": "el restaurante", "back": "restaurant", "example": "Cenamos en un restaurante italiano." },
    { "id": "es-0180", "front": "la escuela", "back": "school", "example": "Los niños van a la escuela." },
    { "id": "es-0181", "front": "el hospital", "back": "hospital", "example": "El hospital está muy cerca." },
    { "id": "es-0182", "front": "el parque", "back": "park", "example": "Caminamos por el parque." },
    { "id": "es-0183", "front": "el banco", "back": "bank", "example": "Voy al banco esta tarde." },
    { "id": "es-0184", "front": "el trabajo", "back": "work / job", "example": "Mi trabajo es interesante." },
    { "id": "es-0185", "front": "la oficina", "back": "office", "example": "Trabajo en una oficina pequeña." },
    { "id": "es-0186", "front": "el jefe", "back": "boss", "example": "Mi jefe es muy amable." },
    { "id": "es-0187", "front": "la empresa", "back": "company", "example": "Trabajo en una empresa grande." },
    { "id": "es-0188", "front": "el sol", "back": "sun", "example": "El sol brilla hoy." },
    { "id": "es-0189", "front": "la luna", "back": "moon", "example": "La luna está muy clara esta noche." },
    { "id": "es-0190", "front": "el árbol", "back": "tree", "example": "El árbol da mucha sombra." },
    { "id": "es-0191", "front": "la flor", "back": "flower", "example": "Le regalé una flor a mi madre." },
    { "id": "es-0192", "front": "el mar", "back": "sea", "example": "Me gusta nadar en el mar." },
    { "id": "es-0193", "front": "la montaña", "back": "mountain", "example": "Subimos a la montaña el domingo." },
    { "id": "es-0194", "front": "el cielo", "back": "sky", "example": "El cielo está azul hoy." },
    { "id": "es-0195", "front": "el perro", "back": "dog", "example": "Mi perro corre en el jardín." },
    { "id": "es-0196", "front": "el gato", "back": "cat", "example": "El gato duerme en el sofá." },
    { "id": "es-0197", "front": "el coche", "back": "car", "example": "Mi coche es de color rojo." },
    { "id": "es-0198", "front": "el tren", "back": "train", "example": "El tren sale a las nueve." },
    { "id": "es-0199", "front": "el autobús", "back": "bus", "example": "Tomo el autobús al trabajo." },
    { "id": "es-0200", "front": "el avión", "back": "airplane", "example": "El avión llega a las seis." },
    { "id": "es-0201", "front": "la bicicleta", "back": "bicycle", "example": "Voy al parque en bicicleta." },
    { "id": "es-0202", "front": "grande", "back": "big", "example": "Tienen una casa muy grande." },
    { "id": "es-0203", "front": "pequeño", "back": "small", "example": "Mi cuarto es pequeño." },
    { "id": "es-0204", "front": "bueno", "back": "good", "example": "Es un buen amigo." },
    { "id": "es-0205", "front": "malo", "back": "bad", "example": "Hoy hace mal tiempo." },
    { "id": "es-0206", "front": "nuevo", "back": "new", "example": "Compré un coche nuevo." },
    { "id": "es-0207", "front": "viejo", "back": "old", "example": "Ese edificio es muy viejo." },
    { "id": "es-0208", "front": "bonito", "back": "pretty / nice", "example": "Es un pueblo muy bonito." },
    { "id": "es-0209", "front": "alto", "back": "tall / high", "example": "Mi hermano es muy alto." },
    { "id": "es-0210", "front": "bajo", "back": "short / low", "example": "La mesa es muy baja." },
    { "id": "es-0211", "front": "fácil", "back": "easy", "example": "El examen fue muy fácil." },
    { "id": "es-0212", "front": "difícil", "back": "difficult", "example": "Esta pregunta es difícil." },
    { "id": "es-0213", "front": "caliente", "back": "hot", "example": "El café está muy caliente." },
    { "id": "es-0214", "front": "frío", "back": "cold", "example": "El agua está fría." },
    { "id": "es-0215", "front": "rápido", "back": "fast", "example": "Ese coche es muy rápido." },
    { "id": "es-0216", "front": "feliz", "back": "happy", "example": "Estoy muy feliz hoy." },
    { "id": "es-0217", "front": "triste", "back": "sad", "example": "Se puso triste con la noticia." },
    { "id": "es-0218", "front": "caro", "back": "expensive", "example": "Ese reloj es muy caro." },
    { "id": "es-0219", "front": "barato", "back": "cheap", "example": "Este hotel es muy barato." },
    { "id": "es-0220", "front": "rojo", "back": "red", "example": "Me gusta tu vestido rojo." },
    { "id": "es-0221", "front": "azul", "back": "blue", "example": "El cielo es azul." },
    { "id": "es-0222", "front": "verde", "back": "green", "example": "La hierba es verde." },
    { "id": "es-0223", "front": "amarillo", "back": "yellow", "example": "El sol parece amarillo." },
    { "id": "es-0224", "front": "negro", "back": "black", "example": "Llevo un abrigo negro." },
    { "id": "es-0225", "front": "blanco", "back": "white", "example": "Las paredes son blancas." },
    { "id": "es-0226", "front": "marrón", "back": "brown", "example": "Tiene los ojos de color marrón." },
    { "id": "es-0227", "front": "la derecha", "back": "right", "example": "Gira a la derecha en la esquina." },
    { "id": "es-0228", "front": "la izquierda", "back": "left", "example": "La tienda está a la izquierda." },
    { "id": "es-0229", "front": "cerca", "back": "near", "example": "Vivo cerca de la escuela." },
    { "id": "es-0230", "front": "lejos", "back": "far", "example": "El aeropuerto está muy lejos." },
    { "id": "es-0231", "front": "aquí", "back": "here", "example": "Ven aquí, por favor." },
    { "id": "es-0232", "front": "el tiempo", "back": "weather / time", "example": "Hoy hace buen tiempo." },
    { "id": "es-0233", "front": "la lluvia", "back": "rain", "example": "La lluvia no para de caer." },
    { "id": "es-0234", "front": "el viento", "back": "wind", "example": "Hace mucho viento hoy." },
    { "id": "es-0235", "front": "la nieve", "back": "snow", "example": "La nieve cubre las montañas." },
    { "id": "es-0236", "front": "el calor", "back": "heat", "example": "En verano hace mucho calor." },
    { "id": "es-0237", "front": "el invierno", "back": "winter", "example": "El invierno es muy frío aquí." },
    { "id": "es-0238", "front": "el verano", "back": "summer", "example": "En verano vamos a la playa." },
    { "id": "es-0239", "front": "y", "back": "and", "example": "Quiero pan y leche." },
    { "id": "es-0240", "front": "o", "back": "or", "example": "¿Té o café?" },
    { "id": "es-0241", "front": "pero", "back": "but", "example": "Quiero ir, pero estoy cansado." },
    { "id": "es-0242", "front": "porque", "back": "because", "example": "No salgo porque llueve." },
    { "id": "es-0243", "front": "también", "back": "also / too", "example": "Yo también quiero ir." },
    { "id": "es-0244", "front": "muy", "back": "very", "example": "Estoy muy cansado." },
    { "id": "es-0245", "front": "mucho", "back": "a lot / much", "example": "Te quiero mucho." },
    { "id": "es-0246", "front": "más", "back": "more", "example": "Quiero más café, por favor." },
    { "id": "es-0247", "front": "con", "back": "with", "example": "Voy al cine con mi amiga." },
    { "id": "es-0248", "front": "sin", "back": "without", "example": "Tomo el café sin azúcar." },
    { "id": "es-0249", "front": "el nombre", "back": "name", "example": "¿Cuál es tu nombre?" },
    { "id": "es-0250", "front": "la pregunta", "back": "question", "example": "Tengo una pregunta para ti." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
