// Agora deck. Free.
var deck = {
  "id": "bundled:french",
  "name": "French 250",
  "lang": "fr",
  "cards": [
    { "id": "fr-0001", "front": "bonjour", "back": "hello / good morning", "example": "Bonjour, comment ça va ?" },
    { "id": "fr-0002", "front": "bonsoir", "back": "good evening", "example": "Bonsoir, tu as passé une bonne journée ?" },
    { "id": "fr-0003", "front": "salut", "back": "hi / bye (informal)", "example": "Salut, on se voit demain !" },
    { "id": "fr-0004", "front": "au revoir", "back": "goodbye", "example": "Au revoir, à bientôt !" },
    { "id": "fr-0005", "front": "bonne nuit", "back": "good night", "example": "Bonne nuit, dors bien." },
    { "id": "fr-0006", "front": "merci", "back": "thank you", "example": "Merci beaucoup pour ton aide." },
    { "id": "fr-0007", "front": "de rien", "back": "you're welcome", "example": "Merci ! De rien, c'est normal." },
    { "id": "fr-0008", "front": "s'il vous plaît", "back": "please (formal)", "example": "Un café, s'il vous plaît." },
    { "id": "fr-0009", "front": "s'il te plaît", "back": "please (informal)", "example": "Passe-moi le sel, s'il te plaît." },
    { "id": "fr-0010", "front": "pardon", "back": "sorry / excuse me", "example": "Pardon, je ne vous ai pas entendu." },
    { "id": "fr-0011", "front": "excusez-moi", "back": "excuse me (formal)", "example": "Excusez-moi, où sont les toilettes ?" },
    { "id": "fr-0012", "front": "oui", "back": "yes", "example": "Oui, je suis d'accord." },
    { "id": "fr-0013", "front": "non", "back": "no", "example": "Non, merci, ça va." },
    { "id": "fr-0014", "front": "peut-être", "back": "maybe", "example": "Peut-être que je viendrai ce soir." },
    { "id": "fr-0015", "front": "d'accord", "back": "okay / agreed", "example": "D'accord, on fait comme ça." },
    { "id": "fr-0016", "front": "bienvenue", "back": "welcome", "example": "Bienvenue chez nous !" },
    { "id": "fr-0017", "front": "enchanté", "back": "nice to meet you", "example": "Enchanté, je m'appelle Marc." },
    { "id": "fr-0018", "front": "comment ça va ?", "back": "how are you?", "example": "Salut, comment ça va aujourd'hui ?" },
    { "id": "fr-0019", "front": "ça va", "back": "I'm fine / it's okay", "example": "Ça va bien, et toi ?" },
    { "id": "fr-0020", "front": "à bientôt", "back": "see you soon", "example": "À bientôt, prends soin de toi." },
    { "id": "fr-0021", "front": "à demain", "back": "see you tomorrow", "example": "À demain au bureau !" },
    { "id": "fr-0022", "front": "à tout à l'heure", "back": "see you later (today)", "example": "Je sors un peu, à tout à l'heure." },
    { "id": "fr-0023", "front": "zéro", "back": "zero", "example": "Il fait zéro degré ce matin." },
    { "id": "fr-0024", "front": "un", "back": "one", "example": "J'ai un frère et deux sœurs." },
    { "id": "fr-0025", "front": "deux", "back": "two", "example": "Je voudrais deux croissants." },
    { "id": "fr-0026", "front": "trois", "back": "three", "example": "Le film commence dans trois minutes." },
    { "id": "fr-0027", "front": "quatre", "back": "four", "example": "Nous sommes quatre à table." },
    { "id": "fr-0028", "front": "cinq", "back": "five", "example": "Le train part à cinq heures." },
    { "id": "fr-0029", "front": "six", "back": "six", "example": "Il a six ans aujourd'hui." },
    { "id": "fr-0030", "front": "sept", "back": "seven", "example": "Je travaille sept jours par semaine." },
    { "id": "fr-0031", "front": "huit", "back": "eight", "example": "Le magasin ouvre à huit heures." },
    { "id": "fr-0032", "front": "neuf", "back": "nine", "example": "Il est presque neuf heures." },
    { "id": "fr-0033", "front": "dix", "back": "ten", "example": "J'ai dix euros dans ma poche." },
    { "id": "fr-0034", "front": "onze", "back": "eleven", "example": "Le cours finit à onze heures." },
    { "id": "fr-0035", "front": "douze", "back": "twelve", "example": "Il y a douze mois dans une année." },
    { "id": "fr-0036", "front": "treize", "back": "thirteen", "example": "Ma fille a treize ans." },
    { "id": "fr-0037", "front": "quatorze", "back": "fourteen", "example": "Le bus passe à quatorze heures." },
    { "id": "fr-0038", "front": "quinze", "back": "fifteen", "example": "Attends quinze minutes, s'il te plaît." },
    { "id": "fr-0039", "front": "seize", "back": "sixteen", "example": "Il a seize ans cette année." },
    { "id": "fr-0040", "front": "dix-sept", "back": "seventeen", "example": "Le livre coûte dix-sept euros." },
    { "id": "fr-0041", "front": "dix-huit", "back": "eighteen", "example": "On est majeur à dix-huit ans." },
    { "id": "fr-0042", "front": "dix-neuf", "back": "nineteen", "example": "Elle habite au dix-neuf de cette rue." },
    { "id": "fr-0043", "front": "vingt", "back": "twenty", "example": "Il me reste vingt minutes." },
    { "id": "fr-0044", "front": "trente", "back": "thirty", "example": "Ce mois a trente jours." },
    { "id": "fr-0045", "front": "quarante", "back": "forty", "example": "Mon père a quarante ans." },
    { "id": "fr-0046", "front": "cinquante", "back": "fifty", "example": "Le ticket coûte cinquante euros." },
    { "id": "fr-0047", "front": "soixante", "back": "sixty", "example": "Une heure fait soixante minutes." },
    { "id": "fr-0048", "front": "soixante-dix", "back": "seventy", "example": "Ma grand-mère a soixante-dix ans." },
    { "id": "fr-0049", "front": "quatre-vingts", "back": "eighty", "example": "Il y a quatre-vingts élèves ici." },
    { "id": "fr-0050", "front": "quatre-vingt-dix", "back": "ninety", "example": "Le trajet dure quatre-vingt-dix minutes." },
    { "id": "fr-0051", "front": "cent", "back": "one hundred", "example": "Ce manteau coûte cent euros." },
    { "id": "fr-0052", "front": "mille", "back": "one thousand", "example": "La ville compte mille habitants." },
    { "id": "fr-0053", "front": "lundi", "back": "Monday", "example": "Je commence le travail lundi." },
    { "id": "fr-0054", "front": "mardi", "back": "Tuesday", "example": "Mardi, j'ai un rendez-vous." },
    { "id": "fr-0055", "front": "mercredi", "back": "Wednesday", "example": "Les enfants ne vont pas à l'école le mercredi." },
    { "id": "fr-0056", "front": "jeudi", "back": "Thursday", "example": "On dîne ensemble jeudi soir." },
    { "id": "fr-0057", "front": "vendredi", "back": "Friday", "example": "Vendredi, c'est presque le week-end." },
    { "id": "fr-0058", "front": "samedi", "back": "Saturday", "example": "Samedi, je fais les courses." },
    { "id": "fr-0059", "front": "dimanche", "back": "Sunday", "example": "Le dimanche, je me repose." },
    { "id": "fr-0060", "front": "janvier", "back": "January", "example": "Mon anniversaire est en janvier." },
    { "id": "fr-0061", "front": "février", "back": "February", "example": "Il neige souvent en février." },
    { "id": "fr-0062", "front": "mars", "back": "March", "example": "Le printemps commence en mars." },
    { "id": "fr-0063", "front": "avril", "back": "April", "example": "En avril, il pleut beaucoup." },
    { "id": "fr-0064", "front": "mai", "back": "May", "example": "Nous partons en vacances en mai." },
    { "id": "fr-0065", "front": "juin", "back": "June", "example": "Les examens sont en juin." },
    { "id": "fr-0066", "front": "juillet", "back": "July", "example": "Il fait très chaud en juillet." },
    { "id": "fr-0067", "front": "août", "back": "August", "example": "Beaucoup de gens sont en congé en août." },
    { "id": "fr-0068", "front": "septembre", "back": "September", "example": "La rentrée a lieu en septembre." },
    { "id": "fr-0069", "front": "octobre", "back": "October", "example": "Les feuilles tombent en octobre." },
    { "id": "fr-0070", "front": "novembre", "back": "November", "example": "Il fait froid en novembre." },
    { "id": "fr-0071", "front": "décembre", "back": "December", "example": "Noël est en décembre." },
    { "id": "fr-0072", "front": "aujourd'hui", "back": "today", "example": "Aujourd'hui, il fait beau." },
    { "id": "fr-0073", "front": "demain", "back": "tomorrow", "example": "Demain, je vais au travail." },
    { "id": "fr-0074", "front": "hier", "back": "yesterday", "example": "Hier, j'ai vu un ami." },
    { "id": "fr-0075", "front": "maintenant", "back": "now", "example": "Je dois partir maintenant." },
    { "id": "fr-0076", "front": "le matin", "back": "the morning", "example": "Le matin, je bois un café." },
    { "id": "fr-0077", "front": "l'après-midi", "back": "the afternoon", "example": "L'après-midi, je fais une sieste." },
    { "id": "fr-0078", "front": "le soir", "back": "the evening", "example": "Le soir, je lis un livre." },
    { "id": "fr-0079", "front": "la nuit", "back": "the night", "example": "La nuit, tout est calme." },
    { "id": "fr-0080", "front": "l'heure", "back": "the hour / time", "example": "Quelle heure est-il ?" },
    { "id": "fr-0081", "front": "la minute", "back": "the minute", "example": "Attends une minute, j'arrive." },
    { "id": "fr-0082", "front": "la semaine", "back": "the week", "example": "Cette semaine est très chargée." },
    { "id": "fr-0083", "front": "le mois", "back": "the month", "example": "Le mois prochain, je déménage." },
    { "id": "fr-0084", "front": "l'année", "back": "the year", "example": "Bonne année à tous !" },
    { "id": "fr-0085", "front": "le jour", "back": "the day", "example": "Quel beau jour aujourd'hui !" },
    { "id": "fr-0086", "front": "qui", "back": "who", "example": "Qui est à la porte ?" },
    { "id": "fr-0087", "front": "quoi", "back": "what", "example": "Quoi ? Je n'ai pas compris." },
    { "id": "fr-0088", "front": "où", "back": "where", "example": "Où habites-tu ?" },
    { "id": "fr-0089", "front": "quand", "back": "when", "example": "Quand arrives-tu ?" },
    { "id": "fr-0090", "front": "pourquoi", "back": "why", "example": "Pourquoi es-tu triste ?" },
    { "id": "fr-0091", "front": "comment", "back": "how", "example": "Comment tu t'appelles ?" },
    { "id": "fr-0092", "front": "combien", "back": "how much / how many", "example": "Combien ça coûte ?" },
    { "id": "fr-0093", "front": "quel", "back": "which / what (m.)", "example": "Quel est ton nom ?" },
    { "id": "fr-0094", "front": "je", "back": "I", "example": "Je suis fatigué ce soir." },
    { "id": "fr-0095", "front": "tu", "back": "you (informal)", "example": "Tu es très gentil." },
    { "id": "fr-0096", "front": "il", "back": "he / it", "example": "Il travaille à Paris." },
    { "id": "fr-0097", "front": "elle", "back": "she / it", "example": "Elle aime le chocolat." },
    { "id": "fr-0098", "front": "nous", "back": "we", "example": "Nous allons au cinéma." },
    { "id": "fr-0099", "front": "vous", "back": "you (formal/plural)", "example": "Vous êtes très aimable." },
    { "id": "fr-0100", "front": "ils", "back": "they (m.)", "example": "Ils jouent au football." },
    { "id": "fr-0101", "front": "elles", "back": "they (f.)", "example": "Elles chantent ensemble." },
    { "id": "fr-0102", "front": "on", "back": "we / one (informal)", "example": "On va manger maintenant ?" },
    { "id": "fr-0103", "front": "moi", "back": "me", "example": "C'est pour moi ?" },
    { "id": "fr-0104", "front": "toi", "back": "you (stressed)", "example": "Et toi, comment vas-tu ?" },
    { "id": "fr-0105", "front": "être", "back": "to be", "example": "Je veux être heureux." },
    { "id": "fr-0106", "front": "avoir", "back": "to have", "example": "J'aimerais avoir un chien." },
    { "id": "fr-0107", "front": "faire", "back": "to do / to make", "example": "Que veux-tu faire ce soir ?" },
    { "id": "fr-0108", "front": "aller", "back": "to go", "example": "Je dois aller au travail." },
    { "id": "fr-0109", "front": "venir", "back": "to come", "example": "Tu peux venir avec moi." },
    { "id": "fr-0110", "front": "voir", "back": "to see", "example": "J'aimerais voir ce film." },
    { "id": "fr-0111", "front": "savoir", "back": "to know (a fact)", "example": "Je veux savoir la vérité." },
    { "id": "fr-0112", "front": "pouvoir", "back": "to be able to / can", "example": "Tu peux m'aider ?" },
    { "id": "fr-0113", "front": "vouloir", "back": "to want", "example": "Je veux un verre d'eau." },
    { "id": "fr-0114", "front": "devoir", "back": "to have to / must", "example": "Je dois partir tôt." },
    { "id": "fr-0115", "front": "prendre", "back": "to take", "example": "Je vais prendre le train." },
    { "id": "fr-0116", "front": "parler", "back": "to speak", "example": "Tu peux parler plus lentement ?" },
    { "id": "fr-0117", "front": "manger", "back": "to eat", "example": "On va manger au restaurant." },
    { "id": "fr-0118", "front": "boire", "back": "to drink", "example": "Je voudrais boire un café." },
    { "id": "fr-0119", "front": "dormir", "back": "to sleep", "example": "J'ai besoin de dormir." },
    { "id": "fr-0120", "front": "aimer", "back": "to like / to love", "example": "J'aime beaucoup ce livre." },
    { "id": "fr-0121", "front": "donner", "back": "to give", "example": "Peux-tu me donner ce stylo ?" },
    { "id": "fr-0122", "front": "trouver", "back": "to find", "example": "Je ne trouve pas mes clés." },
    { "id": "fr-0123", "front": "dire", "back": "to say / to tell", "example": "Que veux-tu dire ?" },
    { "id": "fr-0124", "front": "comprendre", "back": "to understand", "example": "Je ne comprends pas la question." },
    { "id": "fr-0125", "front": "acheter", "back": "to buy", "example": "Je dois acheter du pain." },
    { "id": "fr-0126", "front": "travailler", "back": "to work", "example": "Je travaille dans un bureau." },
    { "id": "fr-0127", "front": "habiter", "back": "to live (reside)", "example": "J'habite à Lyon." },
    { "id": "fr-0128", "front": "écouter", "back": "to listen", "example": "J'aime écouter de la musique." },
    { "id": "fr-0129", "front": "regarder", "back": "to watch / to look", "example": "On regarde un film ce soir." },
    { "id": "fr-0130", "front": "lire", "back": "to read", "example": "J'aime lire avant de dormir." },
    { "id": "fr-0131", "front": "écrire", "back": "to write", "example": "Je dois écrire une lettre." },
    { "id": "fr-0132", "front": "attendre", "back": "to wait", "example": "Attends-moi devant la porte." },
    { "id": "fr-0133", "front": "ouvrir", "back": "to open", "example": "Peux-tu ouvrir la fenêtre ?" },
    { "id": "fr-0134", "front": "fermer", "back": "to close", "example": "N'oublie pas de fermer la porte." },
    { "id": "fr-0135", "front": "le père", "back": "the father", "example": "Mon père est médecin." },
    { "id": "fr-0136", "front": "la mère", "back": "the mother", "example": "Ma mère cuisine très bien." },
    { "id": "fr-0137", "front": "le fils", "back": "the son", "example": "Leur fils a cinq ans." },
    { "id": "fr-0138", "front": "la fille", "back": "the daughter / girl", "example": "Sa fille étudie à Paris." },
    { "id": "fr-0139", "front": "le frère", "back": "the brother", "example": "Mon frère habite à Nice." },
    { "id": "fr-0140", "front": "la sœur", "back": "the sister", "example": "Ma sœur est plus jeune que moi." },
    { "id": "fr-0141", "front": "les parents", "back": "the parents", "example": "Mes parents sont en voyage." },
    { "id": "fr-0142", "front": "l'enfant", "back": "the child", "example": "L'enfant joue dans le jardin." },
    { "id": "fr-0143", "front": "le mari", "back": "the husband", "example": "Son mari travaille à l'hôpital." },
    { "id": "fr-0144", "front": "la femme", "back": "the wife / woman", "example": "Sa femme est avocate." },
    { "id": "fr-0145", "front": "l'ami", "back": "the friend (m.)", "example": "C'est un ami d'enfance." },
    { "id": "fr-0146", "front": "l'amie", "back": "the friend (f.)", "example": "Mon amie arrive ce soir." },
    { "id": "fr-0147", "front": "l'homme", "back": "the man", "example": "Cet homme est très grand." },
    { "id": "fr-0148", "front": "le bébé", "back": "the baby", "example": "Le bébé dort dans son lit." },
    { "id": "fr-0149", "front": "le pain", "back": "the bread", "example": "J'achète du pain tous les matins." },
    { "id": "fr-0150", "front": "l'eau", "back": "the water", "example": "Je voudrais un verre d'eau." },
    { "id": "fr-0151", "front": "le café", "back": "the coffee", "example": "Je bois un café le matin." },
    { "id": "fr-0152", "front": "le thé", "back": "the tea", "example": "Tu préfères le thé ou le café ?" },
    { "id": "fr-0153", "front": "le lait", "back": "the milk", "example": "Il y a du lait dans le frigo." },
    { "id": "fr-0154", "front": "le vin", "back": "the wine", "example": "Un verre de vin rouge, s'il vous plaît." },
    { "id": "fr-0155", "front": "le fromage", "back": "the cheese", "example": "Ce fromage vient de Normandie." },
    { "id": "fr-0156", "front": "la viande", "back": "the meat", "example": "Je ne mange pas de viande." },
    { "id": "fr-0157", "front": "le poisson", "back": "the fish", "example": "Le poisson est très frais ici." },
    { "id": "fr-0158", "front": "le fruit", "back": "the fruit", "example": "Je mange un fruit chaque jour." },
    { "id": "fr-0159", "front": "le légume", "back": "the vegetable", "example": "Mange tes légumes, c'est bon pour toi." },
    { "id": "fr-0160", "front": "la pomme", "back": "the apple", "example": "Cette pomme est très sucrée." },
    { "id": "fr-0161", "front": "le repas", "back": "the meal", "example": "Le repas était délicieux." },
    { "id": "fr-0162", "front": "le petit-déjeuner", "back": "breakfast", "example": "Je prends mon petit-déjeuner à huit heures." },
    { "id": "fr-0163", "front": "le déjeuner", "back": "lunch", "example": "Le déjeuner est servi à midi." },
    { "id": "fr-0164", "front": "le dîner", "back": "dinner", "example": "Le dîner est prêt." },
    { "id": "fr-0165", "front": "la maison", "back": "the house", "example": "Leur maison est près de la mer." },
    { "id": "fr-0166", "front": "l'appartement", "back": "the apartment", "example": "Mon appartement est petit mais lumineux." },
    { "id": "fr-0167", "front": "la chambre", "back": "the bedroom", "example": "Ma chambre est au premier étage." },
    { "id": "fr-0168", "front": "la cuisine", "back": "the kitchen", "example": "La cuisine est très moderne." },
    { "id": "fr-0169", "front": "la salle de bain", "back": "the bathroom", "example": "La salle de bain est au fond du couloir." },
    { "id": "fr-0170", "front": "la porte", "back": "the door", "example": "Ferme la porte, il fait froid." },
    { "id": "fr-0171", "front": "la fenêtre", "back": "the window", "example": "Ouvre la fenêtre pour aérer." },
    { "id": "fr-0172", "front": "la table", "back": "the table", "example": "Le repas est sur la table." },
    { "id": "fr-0173", "front": "la chaise", "back": "the chair", "example": "Prends une chaise et assieds-toi." },
    { "id": "fr-0174", "front": "le lit", "back": "the bed", "example": "Le lit est très confortable." },
    { "id": "fr-0175", "front": "la tête", "back": "the head", "example": "J'ai mal à la tête." },
    { "id": "fr-0176", "front": "la main", "back": "the hand", "example": "Donne-moi la main." },
    { "id": "fr-0177", "front": "le pied", "back": "the foot", "example": "J'ai mal au pied gauche." },
    { "id": "fr-0178", "front": "l'œil", "back": "the eye", "example": "Il a quelque chose dans l'œil." },
    { "id": "fr-0179", "front": "le bras", "back": "the arm", "example": "Elle a mal au bras." },
    { "id": "fr-0180", "front": "la jambe", "back": "the leg", "example": "Il s'est blessé à la jambe." },
    { "id": "fr-0181", "front": "le cœur", "back": "the heart", "example": "Mon cœur bat très vite." },
    { "id": "fr-0182", "front": "la ville", "back": "the city / town", "example": "J'habite dans une grande ville." },
    { "id": "fr-0183", "front": "la rue", "back": "the street", "example": "La rue est très calme la nuit." },
    { "id": "fr-0184", "front": "le magasin", "back": "the shop / store", "example": "Le magasin ferme à dix-neuf heures." },
    { "id": "fr-0185", "front": "le marché", "back": "the market", "example": "Je vais au marché le samedi." },
    { "id": "fr-0186", "front": "le restaurant", "back": "the restaurant", "example": "On dîne au restaurant ce soir." },
    { "id": "fr-0187", "front": "l'école", "back": "the school", "example": "Les enfants vont à l'école à pied." },
    { "id": "fr-0188", "front": "l'hôpital", "back": "the hospital", "example": "L'hôpital est près d'ici." },
    { "id": "fr-0189", "front": "la gare", "back": "the train station", "example": "La gare est à dix minutes." },
    { "id": "fr-0190", "front": "l'aéroport", "back": "the airport", "example": "Nous partons à l'aéroport tôt." },
    { "id": "fr-0191", "front": "la banque", "back": "the bank", "example": "La banque ouvre à neuf heures." },
    { "id": "fr-0192", "front": "le travail", "back": "the work / job", "example": "J'aime beaucoup mon travail." },
    { "id": "fr-0193", "front": "le bureau", "back": "the office / desk", "example": "Je suis au bureau jusqu'à dix-huit heures." },
    { "id": "fr-0194", "front": "l'argent", "back": "the money", "example": "Je n'ai pas assez d'argent." },
    { "id": "fr-0195", "front": "l'arbre", "back": "the tree", "example": "L'arbre devant la maison est très vieux." },
    { "id": "fr-0196", "front": "la fleur", "back": "the flower", "example": "Cette fleur sent très bon." },
    { "id": "fr-0197", "front": "le soleil", "back": "the sun", "example": "Le soleil brille aujourd'hui." },
    { "id": "fr-0198", "front": "la mer", "back": "the sea", "example": "La mer est calme ce matin." },
    { "id": "fr-0199", "front": "la montagne", "back": "the mountain", "example": "On part à la montagne cet hiver." },
    { "id": "fr-0200", "front": "le ciel", "back": "the sky", "example": "Le ciel est bleu aujourd'hui." },
    { "id": "fr-0201", "front": "le chien", "back": "the dog", "example": "Mon chien adore courir dans le parc." },
    { "id": "fr-0202", "front": "le chat", "back": "the cat", "example": "Le chat dort sur le canapé." },
    { "id": "fr-0203", "front": "la voiture", "back": "the car", "example": "Ma voiture est garée dehors." },
    { "id": "fr-0204", "front": "le train", "back": "the train", "example": "Le train arrive dans cinq minutes." },
    { "id": "fr-0205", "front": "le bus", "back": "the bus", "example": "Je prends le bus pour aller au travail." },
    { "id": "fr-0206", "front": "le vélo", "back": "the bicycle", "example": "Elle va à l'école à vélo." },
    { "id": "fr-0207", "front": "l'avion", "back": "the airplane", "example": "L'avion décolle à midi." },
    { "id": "fr-0208", "front": "le livre", "back": "the book", "example": "Ce livre est passionnant." },
    { "id": "fr-0209", "front": "le téléphone", "back": "the phone", "example": "Mon téléphone n'a plus de batterie." },
    { "id": "fr-0210", "front": "l'ordinateur", "back": "the computer", "example": "Je travaille sur mon ordinateur." },
    { "id": "fr-0211", "front": "grand", "back": "big / tall", "example": "Il habite dans une grande maison." },
    { "id": "fr-0212", "front": "petit", "back": "small / little", "example": "C'est un petit village tranquille." },
    { "id": "fr-0213", "front": "bon", "back": "good", "example": "Ce gâteau est très bon." },
    { "id": "fr-0214", "front": "mauvais", "back": "bad", "example": "Il fait mauvais temps aujourd'hui." },
    { "id": "fr-0215", "front": "beau", "back": "beautiful / handsome", "example": "Quel beau paysage !" },
    { "id": "fr-0216", "front": "joli", "back": "pretty", "example": "Elle porte une jolie robe." },
    { "id": "fr-0217", "front": "nouveau", "back": "new", "example": "J'ai acheté un nouveau manteau." },
    { "id": "fr-0218", "front": "vieux", "back": "old", "example": "C'est un vieux livre de mon grand-père." },
    { "id": "fr-0219", "front": "jeune", "back": "young", "example": "Elle est encore très jeune." },
    { "id": "fr-0220", "front": "chaud", "back": "hot / warm", "example": "Le café est encore chaud." },
    { "id": "fr-0221", "front": "froid", "back": "cold", "example": "L'eau est trop froide pour nager." },
    { "id": "fr-0222", "front": "facile", "back": "easy", "example": "Cet exercice est très facile." },
    { "id": "fr-0223", "front": "difficile", "back": "difficult", "example": "Le français n'est pas si difficile." },
    { "id": "fr-0224", "front": "content", "back": "happy / glad", "example": "Je suis content de te voir." },
    { "id": "fr-0225", "front": "fatigué", "back": "tired", "example": "Je suis très fatigué ce soir." },
    { "id": "fr-0226", "front": "cher", "back": "expensive / dear", "example": "Ce restaurant est trop cher." },
    { "id": "fr-0227", "front": "rouge", "back": "red", "example": "J'aime ta veste rouge." },
    { "id": "fr-0228", "front": "bleu", "back": "blue", "example": "Le ciel est bleu aujourd'hui." },
    { "id": "fr-0229", "front": "vert", "back": "green", "example": "Les feuilles sont vertes au printemps." },
    { "id": "fr-0230", "front": "jaune", "back": "yellow", "example": "Le soleil est jaune et brillant." },
    { "id": "fr-0231", "front": "noir", "back": "black", "example": "Il porte un costume noir." },
    { "id": "fr-0232", "front": "blanc", "back": "white", "example": "La neige est toute blanche." },
    { "id": "fr-0233", "front": "à droite", "back": "to/on the right", "example": "Tournez à droite après la banque." },
    { "id": "fr-0234", "front": "à gauche", "back": "to/on the left", "example": "La pharmacie est à gauche." },
    { "id": "fr-0235", "front": "tout droit", "back": "straight ahead", "example": "Continuez tout droit jusqu'au feu." },
    { "id": "fr-0236", "front": "ici", "back": "here", "example": "Viens ici, s'il te plaît." },
    { "id": "fr-0237", "front": "là", "back": "there", "example": "Pose le sac là, sur la chaise." },
    { "id": "fr-0238", "front": "près de", "back": "near / close to", "example": "J'habite près de la gare." },
    { "id": "fr-0239", "front": "loin de", "back": "far from", "example": "L'aéroport est loin du centre-ville." },
    { "id": "fr-0240", "front": "le temps", "back": "the weather / time", "example": "Quel temps fait-il aujourd'hui ?" },
    { "id": "fr-0241", "front": "la pluie", "back": "the rain", "example": "La pluie n'a pas arrêté de la journée." },
    { "id": "fr-0242", "front": "la neige", "back": "the snow", "example": "La neige recouvre les montagnes." },
    { "id": "fr-0243", "front": "le vent", "back": "the wind", "example": "Le vent souffle très fort ce soir." },
    { "id": "fr-0244", "front": "il fait beau", "back": "the weather is nice", "example": "Aujourd'hui, il fait beau et chaud." },
    { "id": "fr-0245", "front": "il pleut", "back": "it's raining", "example": "Prends un parapluie, il pleut." },
    { "id": "fr-0246", "front": "beaucoup", "back": "a lot / much", "example": "Merci beaucoup pour ton aide." },
    { "id": "fr-0247", "front": "un peu", "back": "a little", "example": "Je parle un peu français." },
    { "id": "fr-0248", "front": "très", "back": "very", "example": "Ce film est très intéressant." },
    { "id": "fr-0249", "front": "toujours", "back": "always", "example": "Elle est toujours en retard." },
    { "id": "fr-0250", "front": "jamais", "back": "never", "example": "Je ne bois jamais de café le soir." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
