// Agora deck. Free.
var deck = {
  "id": "bundled:italian",
  "name": "Italian 250",
  "lang": "it",
  "cards": [
    { "id": "it-0001", "front": "ciao", "back": "hi / bye", "example": "Ciao, come stai?" },
    { "id": "it-0002", "front": "buongiorno", "back": "good morning", "example": "Buongiorno, signora!" },
    { "id": "it-0003", "front": "buonasera", "back": "good evening", "example": "Buonasera a tutti." },
    { "id": "it-0004", "front": "buonanotte", "back": "good night", "example": "Buonanotte, a domani." },
    { "id": "it-0005", "front": "arrivederci", "back": "goodbye", "example": "Arrivederci, dottore." },
    { "id": "it-0006", "front": "grazie", "back": "thank you", "example": "Grazie mille per l'aiuto." },
    { "id": "it-0007", "front": "prego", "back": "you're welcome", "example": "Prego, si accomodi." },
    { "id": "it-0008", "front": "per favore", "back": "please", "example": "Un caffè, per favore." },
    { "id": "it-0009", "front": "scusa", "back": "sorry / excuse me (informal)", "example": "Scusa, non ti ho sentito." },
    { "id": "it-0010", "front": "scusi", "back": "excuse me (formal)", "example": "Scusi, dov'è la stazione?" },
    { "id": "it-0011", "front": "sì", "back": "yes", "example": "Sì, sono d'accordo." },
    { "id": "it-0012", "front": "no", "back": "no", "example": "No, non posso venire." },
    { "id": "it-0013", "front": "zero", "back": "zero", "example": "Ho zero euro in tasca." },
    { "id": "it-0014", "front": "uno", "back": "one", "example": "Voglio solo un caffè." },
    { "id": "it-0015", "front": "due", "back": "two", "example": "Ho due fratelli." },
    { "id": "it-0016", "front": "tre", "back": "three", "example": "Sono le tre del pomeriggio." },
    { "id": "it-0017", "front": "quattro", "back": "four", "example": "Abbiamo quattro sedie." },
    { "id": "it-0018", "front": "cinque", "back": "five", "example": "Il treno parte alle cinque." },
    { "id": "it-0019", "front": "sei", "back": "six", "example": "Ci sono sei uova nel frigo." },
    { "id": "it-0020", "front": "sette", "back": "seven", "example": "La settimana ha sette giorni." },
    { "id": "it-0021", "front": "otto", "back": "eight", "example": "Lavoro otto ore al giorno." },
    { "id": "it-0022", "front": "nove", "back": "nine", "example": "Mio figlio ha nove anni." },
    { "id": "it-0023", "front": "dieci", "back": "ten", "example": "Costa dieci euro." },
    { "id": "it-0024", "front": "undici", "back": "eleven", "example": "Ci vediamo alle undici." },
    { "id": "it-0025", "front": "dodici", "back": "twelve", "example": "Un anno ha dodici mesi." },
    { "id": "it-0026", "front": "tredici", "back": "thirteen", "example": "Ho tredici messaggi nuovi." },
    { "id": "it-0027", "front": "quattordici", "back": "fourteen", "example": "La festa è il quattordici." },
    { "id": "it-0028", "front": "quindici", "back": "fifteen", "example": "Arrivo tra quindici minuti." },
    { "id": "it-0029", "front": "sedici", "back": "sixteen", "example": "Mia sorella ha sedici anni." },
    { "id": "it-0030", "front": "diciassette", "back": "seventeen", "example": "Sono nato il diciassette marzo." },
    { "id": "it-0031", "front": "diciotto", "back": "eighteen", "example": "A diciotto anni sei maggiorenne." },
    { "id": "it-0032", "front": "diciannove", "back": "nineteen", "example": "Ho diciannove libri da leggere." },
    { "id": "it-0033", "front": "venti", "back": "twenty", "example": "Ci sono venti studenti in classe." },
    { "id": "it-0034", "front": "trenta", "back": "thirty", "example": "Mio padre ha trenta dipendenti." },
    { "id": "it-0035", "front": "quaranta", "back": "forty", "example": "La strada è lunga quaranta chilometri." },
    { "id": "it-0036", "front": "cinquanta", "back": "fifty", "example": "Ho cinquanta euro nel portafoglio." },
    { "id": "it-0037", "front": "sessanta", "back": "sixty", "example": "Un'ora ha sessanta minuti." },
    { "id": "it-0038", "front": "settanta", "back": "seventy", "example": "Mia nonna ha settanta anni." },
    { "id": "it-0039", "front": "ottanta", "back": "eighty", "example": "Il film dura ottanta minuti." },
    { "id": "it-0040", "front": "novanta", "back": "ninety", "example": "Ho corso per novanta minuti." },
    { "id": "it-0041", "front": "cento", "back": "hundred", "example": "Questo libro ha cento pagine." },
    { "id": "it-0042", "front": "mille", "back": "thousand", "example": "Ho speso mille euro." },
    { "id": "it-0043", "front": "lunedì", "back": "Monday", "example": "Lunedì comincia la scuola." },
    { "id": "it-0044", "front": "martedì", "back": "Tuesday", "example": "Martedì ho una riunione." },
    { "id": "it-0045", "front": "mercoledì", "back": "Wednesday", "example": "Mercoledì vado dal medico." },
    { "id": "it-0046", "front": "giovedì", "back": "Thursday", "example": "Giovedì sera usciamo insieme." },
    { "id": "it-0047", "front": "venerdì", "back": "Friday", "example": "Venerdì finisco di lavorare presto." },
    { "id": "it-0048", "front": "sabato", "back": "Saturday", "example": "Il sabato dormo fino a tardi." },
    { "id": "it-0049", "front": "domenica", "back": "Sunday", "example": "La domenica andiamo in chiesa." },
    { "id": "it-0050", "front": "gennaio", "back": "January", "example": "A gennaio fa molto freddo." },
    { "id": "it-0051", "front": "febbraio", "back": "February", "example": "Febbraio è il mese più corto." },
    { "id": "it-0052", "front": "marzo", "back": "March", "example": "In marzo arriva la primavera." },
    { "id": "it-0053", "front": "aprile", "back": "April", "example": "Ad aprile piove spesso." },
    { "id": "it-0054", "front": "maggio", "back": "May", "example": "A maggio i fiori sbocciano." },
    { "id": "it-0055", "front": "giugno", "back": "June", "example": "A giugno finisce la scuola." },
    { "id": "it-0056", "front": "luglio", "back": "July", "example": "A luglio andiamo al mare." },
    { "id": "it-0057", "front": "agosto", "back": "August", "example": "Ad agosto la città è vuota." },
    { "id": "it-0058", "front": "settembre", "back": "September", "example": "A settembre ricomincia il lavoro." },
    { "id": "it-0059", "front": "ottobre", "back": "October", "example": "In ottobre cadono le foglie." },
    { "id": "it-0060", "front": "novembre", "back": "November", "example": "A novembre fa già freddo." },
    { "id": "it-0061", "front": "dicembre", "back": "December", "example": "A dicembre festeggiamo il Natale." },
    { "id": "it-0062", "front": "oggi", "back": "today", "example": "Oggi è una bella giornata." },
    { "id": "it-0063", "front": "ieri", "back": "yesterday", "example": "Ieri sono andato al cinema." },
    { "id": "it-0064", "front": "domani", "back": "tomorrow", "example": "Domani parto per Roma." },
    { "id": "it-0065", "front": "adesso", "back": "now", "example": "Adesso devo andare." },
    { "id": "it-0066", "front": "sempre", "back": "always", "example": "Bevo sempre un caffè la mattina." },
    { "id": "it-0067", "front": "mai", "back": "never", "example": "Non mangio mai la carne." },
    { "id": "it-0068", "front": "presto", "back": "early / soon", "example": "Mi alzo presto la mattina." },
    { "id": "it-0069", "front": "tardi", "back": "late", "example": "È tardi, andiamo a dormire." },
    { "id": "it-0070", "front": "l'anno", "back": "the year (m)", "example": "L'anno prossimo cambio lavoro." },
    { "id": "it-0071", "front": "il mese", "back": "the month (m)", "example": "Questo mese ho risparmiato poco." },
    { "id": "it-0072", "front": "il giorno", "back": "the day (m)", "example": "Ogni giorno faccio una passeggiata." },
    { "id": "it-0073", "front": "la notte", "back": "the night (f)", "example": "Stanotte ho dormito male." },
    { "id": "it-0074", "front": "l'ora", "back": "the hour (f)", "example": "Che ora è adesso?" },
    { "id": "it-0075", "front": "chi", "back": "who", "example": "Chi è quella ragazza?" },
    { "id": "it-0076", "front": "che cosa", "back": "what", "example": "Che cosa vuoi mangiare?" },
    { "id": "it-0077", "front": "dove", "back": "where", "example": "Dove abiti?" },
    { "id": "it-0078", "front": "quando", "back": "when", "example": "Quando arriva il treno?" },
    { "id": "it-0079", "front": "perché", "back": "why / because", "example": "Perché studi l'italiano?" },
    { "id": "it-0080", "front": "come", "back": "how", "example": "Come ti chiami?" },
    { "id": "it-0081", "front": "quanto", "back": "how much", "example": "Quanto costa questo?" },
    { "id": "it-0082", "front": "quale", "back": "which", "example": "Quale vino preferisci?" },
    { "id": "it-0083", "front": "io", "back": "I", "example": "Io vengo con te." },
    { "id": "it-0084", "front": "tu", "back": "you (informal)", "example": "Tu cosa ne pensi?" },
    { "id": "it-0085", "front": "lui", "back": "he", "example": "Lui lavora in banca." },
    { "id": "it-0086", "front": "lei", "back": "she / you (formal)", "example": "Lei è molto gentile." },
    { "id": "it-0087", "front": "noi", "back": "we", "example": "Noi andiamo al mare." },
    { "id": "it-0088", "front": "voi", "back": "you (plural)", "example": "Voi venite alla festa?" },
    { "id": "it-0089", "front": "loro", "back": "they", "example": "Loro abitano a Milano." },
    { "id": "it-0090", "front": "mi", "back": "me / to me", "example": "Mi piace la pizza." },
    { "id": "it-0091", "front": "questo", "back": "this", "example": "Questo è il mio amico." },
    { "id": "it-0092", "front": "quello", "back": "that", "example": "Quello è troppo caro." },
    { "id": "it-0093", "front": "niente", "back": "nothing", "example": "Non ho capito niente." },
    { "id": "it-0094", "front": "essere", "back": "to be", "example": "Voglio essere felice." },
    { "id": "it-0095", "front": "avere", "back": "to have", "example": "Vorrei avere più tempo." },
    { "id": "it-0096", "front": "fare", "back": "to do / make", "example": "Cosa vuoi fare oggi?" },
    { "id": "it-0097", "front": "andare", "back": "to go", "example": "Devo andare a casa." },
    { "id": "it-0098", "front": "venire", "back": "to come", "example": "Puoi venire alle otto?" },
    { "id": "it-0099", "front": "dire", "back": "to say", "example": "Devo dire una cosa." },
    { "id": "it-0100", "front": "potere", "back": "to be able to", "example": "Non posso uscire stasera." },
    { "id": "it-0101", "front": "volere", "back": "to want", "example": "Voglio un gelato." },
    { "id": "it-0102", "front": "dovere", "back": "to have to", "example": "Devo studiare per l'esame." },
    { "id": "it-0103", "front": "sapere", "back": "to know (a fact)", "example": "Non so dove sia." },
    { "id": "it-0104", "front": "conoscere", "back": "to know (a person)", "example": "Vorrei conoscere i tuoi amici." },
    { "id": "it-0105", "front": "vedere", "back": "to see", "example": "Non riesco a vedere bene." },
    { "id": "it-0106", "front": "sentire", "back": "to hear / feel", "example": "Non ti sento, parla più forte." },
    { "id": "it-0107", "front": "parlare", "back": "to speak", "example": "Parli italiano molto bene." },
    { "id": "it-0108", "front": "mangiare", "back": "to eat", "example": "Stasera vorrei mangiare il pesce." },
    { "id": "it-0109", "front": "bere", "back": "to drink", "example": "Vuoi bere qualcosa?" },
    { "id": "it-0110", "front": "dormire", "back": "to sleep", "example": "Voglio dormire fino a tardi." },
    { "id": "it-0111", "front": "lavorare", "back": "to work", "example": "Devo lavorare fino a sera." },
    { "id": "it-0112", "front": "studiare", "back": "to study", "example": "Mi piace studiare le lingue." },
    { "id": "it-0113", "front": "leggere", "back": "to read", "example": "Adoro leggere prima di dormire." },
    { "id": "it-0114", "front": "scrivere", "back": "to write", "example": "Devo scrivere una lettera." },
    { "id": "it-0115", "front": "comprare", "back": "to buy", "example": "Voglio comprare un regalo." },
    { "id": "it-0116", "front": "pagare", "back": "to pay", "example": "Posso pagare con la carta?" },
    { "id": "it-0117", "front": "aprire", "back": "to open", "example": "Puoi aprire la finestra?" },
    { "id": "it-0118", "front": "chiudere", "back": "to close", "example": "Chiudi la porta, per favore." },
    { "id": "it-0119", "front": "dare", "back": "to give", "example": "Mi puoi dare una mano?" },
    { "id": "it-0120", "front": "prendere", "back": "to take", "example": "Prendo il treno delle nove." },
    { "id": "it-0121", "front": "trovare", "back": "to find", "example": "Non riesco a trovare le scarpe." },
    { "id": "it-0122", "front": "pensare", "back": "to think", "example": "Penso che tu abbia ragione." },
    { "id": "it-0123", "front": "capire", "back": "to understand", "example": "Non riesco a capire il problema." },
    { "id": "it-0124", "front": "aspettare", "back": "to wait", "example": "Ti aspetto davanti al bar." },
    { "id": "it-0125", "front": "chiamare", "back": "to call", "example": "Ti chiamo domani mattina." },
    { "id": "it-0126", "front": "partire", "back": "to leave / depart", "example": "Devo partire alle sei." },
    { "id": "it-0127", "front": "arrivare", "back": "to arrive", "example": "Il treno deve arrivare alle dieci." },
    { "id": "it-0128", "front": "la famiglia", "back": "the family (f)", "example": "La mia famiglia è numerosa." },
    { "id": "it-0129", "front": "la madre", "back": "the mother (f)", "example": "Mia madre cucina benissimo." },
    { "id": "it-0130", "front": "il padre", "back": "the father (m)", "example": "Mio padre lavora in ufficio." },
    { "id": "it-0131", "front": "il figlio", "back": "the son (m)", "example": "Suo figlio studia medicina." },
    { "id": "it-0132", "front": "la figlia", "back": "the daughter (f)", "example": "La loro figlia ha due anni." },
    { "id": "it-0133", "front": "il fratello", "back": "the brother (m)", "example": "Mio fratello vive a Torino." },
    { "id": "it-0134", "front": "la sorella", "back": "the sister (f)", "example": "Mia sorella è più giovane di me." },
    { "id": "it-0135", "front": "il nonno", "back": "the grandfather (m)", "example": "Il nonno racconta belle storie." },
    { "id": "it-0136", "front": "la nonna", "back": "the grandmother (f)", "example": "La nonna fa una torta buonissima." },
    { "id": "it-0137", "front": "l'amico", "back": "the friend (m)", "example": "Vado al cinema con un amico." },
    { "id": "it-0138", "front": "il cibo", "back": "the food (m)", "example": "Il cibo italiano è famoso nel mondo." },
    { "id": "it-0139", "front": "l'acqua", "back": "the water (f)", "example": "Vorrei un bicchiere d'acqua." },
    { "id": "it-0140", "front": "il caffè", "back": "the coffee (m)", "example": "Bevo il caffè ogni mattina." },
    { "id": "it-0141", "front": "il pane", "back": "the bread (m)", "example": "Compro il pane fresco ogni giorno." },
    { "id": "it-0142", "front": "la pasta", "back": "the pasta (f)", "example": "Stasera mangiamo la pasta." },
    { "id": "it-0143", "front": "la pizza", "back": "the pizza (f)", "example": "La pizza margherita è la mia preferita." },
    { "id": "it-0144", "front": "la carne", "back": "the meat (f)", "example": "Non mangio molta carne." },
    { "id": "it-0145", "front": "il pesce", "back": "the fish (m)", "example": "Il pesce è freschissimo qui." },
    { "id": "it-0146", "front": "la frutta", "back": "the fruit (f)", "example": "Mangio la frutta ogni giorno." },
    { "id": "it-0147", "front": "la verdura", "back": "the vegetables (f)", "example": "Devo comprare la verdura." },
    { "id": "it-0148", "front": "lo zucchero", "back": "the sugar (m)", "example": "Vuoi lo zucchero nel caffè?" },
    { "id": "it-0149", "front": "la casa", "back": "the house (f)", "example": "La mia casa è vicino al parco." },
    { "id": "it-0150", "front": "la porta", "back": "the door (f)", "example": "Chiudi la porta, fa freddo." },
    { "id": "it-0151", "front": "la finestra", "back": "the window (f)", "example": "Apri la finestra, per favore." },
    { "id": "it-0152", "front": "il tavolo", "back": "the table (m)", "example": "Metti i piatti sul tavolo." },
    { "id": "it-0153", "front": "la sedia", "back": "the chair (f)", "example": "Questa sedia è molto comoda." },
    { "id": "it-0154", "front": "il letto", "back": "the bed (m)", "example": "Vado a letto presto stasera." },
    { "id": "it-0155", "front": "la cucina", "back": "the kitchen (f)", "example": "La cucina è la stanza più grande." },
    { "id": "it-0156", "front": "il bagno", "back": "the bathroom (m)", "example": "Dov'è il bagno, per favore?" },
    { "id": "it-0157", "front": "il telefono", "back": "the telephone (m)", "example": "Il telefono sta squillando." },
    { "id": "it-0158", "front": "la testa", "back": "the head (f)", "example": "Mi fa male la testa." },
    { "id": "it-0159", "front": "la mano", "back": "the hand (f)", "example": "Dammi la mano per attraversare." },
    { "id": "it-0160", "front": "l'occhio", "back": "the eye (m)", "example": "Ho qualcosa nell'occhio." },
    { "id": "it-0161", "front": "la bocca", "back": "the mouth (f)", "example": "Apri la bocca, dice il dentista." },
    { "id": "it-0162", "front": "il naso", "back": "the nose (m)", "example": "Ho il naso chiuso oggi." },
    { "id": "it-0163", "front": "il piede", "back": "the foot (m)", "example": "Mi fa male il piede destro." },
    { "id": "it-0164", "front": "la gamba", "back": "the leg (f)", "example": "Si è rotta una gamba." },
    { "id": "it-0165", "front": "i capelli", "back": "the hair (m, pl)", "example": "Ha i capelli lunghi e neri." },
    { "id": "it-0166", "front": "la città", "back": "the city (f)", "example": "Roma è una città bellissima." },
    { "id": "it-0167", "front": "il paese", "back": "the village / country (m)", "example": "Vivo in un piccolo paese." },
    { "id": "it-0168", "front": "la strada", "back": "the street / road (f)", "example": "La strada è chiusa per lavori." },
    { "id": "it-0169", "front": "la scuola", "back": "the school (f)", "example": "I bambini vanno a scuola a piedi." },
    { "id": "it-0170", "front": "l'ospedale", "back": "the hospital (m)", "example": "L'ospedale è vicino alla stazione." },
    { "id": "it-0171", "front": "il negozio", "back": "the shop (m)", "example": "Il negozio apre alle nove." },
    { "id": "it-0172", "front": "il mercato", "back": "the market (m)", "example": "Vado al mercato il sabato." },
    { "id": "it-0173", "front": "il ristorante", "back": "the restaurant (m)", "example": "Conosco un buon ristorante qui." },
    { "id": "it-0174", "front": "la banca", "back": "the bank (f)", "example": "La banca chiude all'una." },
    { "id": "it-0175", "front": "la stazione", "back": "the station (f)", "example": "Ci vediamo alla stazione." },
    { "id": "it-0176", "front": "il lavoro", "back": "the work / job (m)", "example": "Cerco un nuovo lavoro." },
    { "id": "it-0177", "front": "il libro", "back": "the book (m)", "example": "Sto leggendo un bel libro." },
    { "id": "it-0178", "front": "i soldi", "back": "the money (m, pl)", "example": "Non ho soldi con me." },
    { "id": "it-0179", "front": "il problema", "back": "the problem (m)", "example": "Abbiamo un piccolo problema." },
    { "id": "it-0180", "front": "il tempo", "back": "the time / weather (m)", "example": "Non ho tempo oggi." },
    { "id": "it-0181", "front": "la cosa", "back": "the thing (f)", "example": "Devo dirti una cosa importante." },
    { "id": "it-0182", "front": "il regalo", "back": "the gift (m)", "example": "Ti ho comprato un regalo." },
    { "id": "it-0183", "front": "il sole", "back": "the sun (m)", "example": "Oggi splende il sole." },
    { "id": "it-0184", "front": "la luna", "back": "the moon (f)", "example": "Stanotte la luna è piena." },
    { "id": "it-0185", "front": "il mare", "back": "the sea (m)", "example": "D'estate andiamo al mare." },
    { "id": "it-0186", "front": "la montagna", "back": "the mountain (f)", "example": "In inverno andiamo in montagna." },
    { "id": "it-0187", "front": "il cane", "back": "the dog (m)", "example": "Il mio cane è molto affettuoso." },
    { "id": "it-0188", "front": "il gatto", "back": "the cat (m)", "example": "Il gatto dorme sul divano." },
    { "id": "it-0189", "front": "la macchina", "back": "the car (f)", "example": "La macchina è nel garage." },
    { "id": "it-0190", "front": "l'autobus", "back": "the bus (m)", "example": "Prendo l'autobus per andare al lavoro." },
    { "id": "it-0191", "front": "il treno", "back": "the train (m)", "example": "Il treno è in ritardo." },
    { "id": "it-0192", "front": "l'aereo", "back": "the airplane (m)", "example": "L'aereo parte tra due ore." },
    { "id": "it-0193", "front": "la bicicletta", "back": "the bicycle (f)", "example": "Vado a scuola in bicicletta." },
    { "id": "it-0194", "front": "la moto", "back": "the motorcycle (f)", "example": "Ha comprato una moto nuova." },
    { "id": "it-0195", "front": "rosso", "back": "red", "example": "Mi piace il vestito rosso." },
    { "id": "it-0196", "front": "blu", "back": "blue", "example": "Il cielo è blu oggi." },
    { "id": "it-0197", "front": "verde", "back": "green", "example": "L'erba è verde e fresca." },
    { "id": "it-0198", "front": "giallo", "back": "yellow", "example": "Il sole è giallo nel disegno." },
    { "id": "it-0199", "front": "nero", "back": "black", "example": "Porto sempre scarpe nere." },
    { "id": "it-0200", "front": "bianco", "back": "white", "example": "La neve è bianca." },
    { "id": "it-0201", "front": "grigio", "back": "gray", "example": "Il cielo è grigio e nuvoloso." },
    { "id": "it-0202", "front": "marrone", "back": "brown", "example": "Ha gli occhi marroni." },
    { "id": "it-0203", "front": "rosa", "back": "pink", "example": "Le ha regalato dei fiori rosa." },
    { "id": "it-0204", "front": "grande", "back": "big", "example": "Vivono in una casa grande." },
    { "id": "it-0205", "front": "piccolo", "back": "small", "example": "Ho un cane piccolo." },
    { "id": "it-0206", "front": "buono", "back": "good / tasty", "example": "Questo gelato è molto buono." },
    { "id": "it-0207", "front": "cattivo", "back": "bad", "example": "Ha un cattivo carattere." },
    { "id": "it-0208", "front": "nuovo", "back": "new", "example": "Ho comprato un telefono nuovo." },
    { "id": "it-0209", "front": "vecchio", "back": "old", "example": "Questo è un libro molto vecchio." },
    { "id": "it-0210", "front": "bello", "back": "beautiful", "example": "Che bella giornata!" },
    { "id": "it-0211", "front": "brutto", "back": "ugly", "example": "Fa un tempo brutto oggi." },
    { "id": "it-0212", "front": "alto", "back": "tall / high", "example": "Mio fratello è molto alto." },
    { "id": "it-0213", "front": "lungo", "back": "long", "example": "È stata una giornata lunga." },
    { "id": "it-0214", "front": "caldo", "back": "hot / warm", "example": "Il caffè è ancora caldo." },
    { "id": "it-0215", "front": "freddo", "back": "cold", "example": "L'acqua è troppo fredda." },
    { "id": "it-0216", "front": "difficile", "back": "difficult", "example": "L'italiano non è difficile." },
    { "id": "it-0217", "front": "felice", "back": "happy", "example": "Sono felice di vederti." },
    { "id": "it-0218", "front": "stanco", "back": "tired", "example": "Sono molto stanco stasera." },
    { "id": "it-0219", "front": "importante", "back": "important", "example": "Ho una riunione importante." },
    { "id": "it-0220", "front": "destra", "back": "right", "example": "Gira a destra al semaforo." },
    { "id": "it-0221", "front": "sinistra", "back": "left", "example": "Il bagno è sulla sinistra." },
    { "id": "it-0222", "front": "dritto", "back": "straight ahead", "example": "Vai sempre dritto per due strade." },
    { "id": "it-0223", "front": "vicino", "back": "near", "example": "Il bar è vicino a casa mia." },
    { "id": "it-0224", "front": "lontano", "back": "far", "example": "La stazione è lontana da qui." },
    { "id": "it-0225", "front": "sotto", "back": "below / under", "example": "Il gatto è sotto il letto." },
    { "id": "it-0226", "front": "qui", "back": "here", "example": "Vieni qui un momento." },
    { "id": "it-0227", "front": "il tempo atmosferico", "back": "the weather (m)", "example": "Com'è il tempo atmosferico oggi?" },
    { "id": "it-0228", "front": "la pioggia", "back": "the rain (f)", "example": "La pioggia non smette mai." },
    { "id": "it-0229", "front": "la neve", "back": "the snow (f)", "example": "La neve copre le montagne." },
    { "id": "it-0230", "front": "il vento", "back": "the wind (m)", "example": "Oggi c'è molto vento." },
    { "id": "it-0231", "front": "la nuvola", "back": "the cloud (f)", "example": "C'è una nuvola nera in cielo." },
    { "id": "it-0232", "front": "il caldo", "back": "the heat (m)", "example": "D'estate fa un gran caldo." },
    { "id": "it-0233", "front": "il freddo", "back": "the cold (m)", "example": "In inverno sento molto il freddo." },
    { "id": "it-0234", "front": "il temporale", "back": "the storm (m)", "example": "Sta arrivando un temporale." },
    { "id": "it-0235", "front": "il cielo", "back": "the sky (m)", "example": "Il cielo è limpido stasera." },
    { "id": "it-0236", "front": "e", "back": "and", "example": "Voglio il pane e il latte." },
    { "id": "it-0237", "front": "o", "back": "or", "example": "Vuoi il tè o il caffè?" },
    { "id": "it-0238", "front": "ma", "back": "but", "example": "Vorrei venire, ma non posso." },
    { "id": "it-0239", "front": "con", "back": "with", "example": "Vengo con te al cinema." },
    { "id": "it-0240", "front": "senza", "back": "without", "example": "Bevo il caffè senza zucchero." },
    { "id": "it-0241", "front": "per", "back": "for / in order to", "example": "Questo regalo è per te." },
    { "id": "it-0242", "front": "in", "back": "in", "example": "Vivo in Italia da tre anni." },
    { "id": "it-0243", "front": "a", "back": "to / at", "example": "Vado a Roma domani." },
    { "id": "it-0244", "front": "di", "back": "of / from", "example": "È la macchina di mio padre." },
    { "id": "it-0245", "front": "da", "back": "from / by", "example": "Vengo da Napoli." },
    { "id": "it-0246", "front": "su", "back": "on", "example": "Il giornale è su quel tavolo." },
    { "id": "it-0247", "front": "molto", "back": "very / a lot", "example": "Sono molto contento." },
    { "id": "it-0248", "front": "troppo", "back": "too much", "example": "Hai mangiato troppo." },
    { "id": "it-0249", "front": "più", "back": "more", "example": "Voglio sapere di più." },
    { "id": "it-0250", "front": "bene", "back": "well", "example": "Sto molto bene, grazie." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
